In [1]:
import keras
from keras.datasets import mnist
from keras.models   import Model
from keras.layers   import LSTM, Input, Dense, TimeDistributed

In [2]:
# Training parameters

batch_size = 32
num_classes = 10
epochs = 5

In [3]:
# embedded dimensions

row_hidden = 128
col_hidden = 128

In [4]:
# DIVIDE THE DATASET INTO TRAINING AND TESTING DATA
(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

In [5]:
# Shape of the Datasets

print(X_train.shape)

(60000, 28, 28)


In [6]:
print(X_test.shape)

(10000, 28, 28)


In [7]:
print(X_train.shape[0])

print(X_test.shape[0])

60000
10000


In [8]:
# Reshaping the Datasets into 4-D Hierarchical form
X_train = X_train.reshape(X_train.shape[0], 28,28,1)

X_test = X_test.reshape(X_test.shape[0], 28,28,1)

In [9]:
print(X_train.shape[0])

60000


In [10]:
print(X_test.shape[0])

10000


In [11]:
print(X_train[:,5])

[[[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 ...

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]

 [[0]
  [0]
  [0]
  ...
  [0]
  [0]
  [0]]]


In [12]:
Y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [13]:
# convert the class vectors into binary class metrices
from tensorflow.keras.utils import to_categorical

Y_train = to_categorical(Y_train, num_classes)

In [14]:
print(Y_train)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [15]:
Y_test = to_categorical(Y_test, num_classes)

In [16]:
print(Y_test)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [17]:
row, col, pixel = X_train.shape[1:]

In [18]:
x = Input(shape = (row, col, pixel))

In [19]:
print(x)

KerasTensor(type_spec=TensorSpec(shape=(None, 28, 28, 1), dtype=tf.float32, name='input_1'), name='input_1', description="created by layer 'input_1'")


In [20]:
# LSTM RNN Algorithm


# Apply LSTM Algorithm to all the encoded rows
encoded_rows = TimeDistributed(LSTM(row_hidden))(x)

# Apply LSTM Algorithm to all columns of the encoded rows
encoded_cols = LSTM(col_hidden)(encoded_rows)

In [21]:
# Performing LSTM function on the dense layer
prediction = Dense(num_classes, activation = 'softmax')(encoded_cols)

In [22]:
print(prediction)

KerasTensor(type_spec=TensorSpec(shape=(None, 10), dtype=tf.float32, name=None), name='dense/Softmax:0', description="created by layer 'dense'")


In [23]:
# calling the RNN Model
model = Model(x,prediction)

In [24]:
print(model)

In [25]:
# COMPILE THE RNN MODEl
model.compile(optimizer = 'RMSProp', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
# TRAIN THE RNN MODEL
model.fit(X_train, Y_train, epochs = 5, batch_size = 100,verbose = 1, validation_data = (X_test, Y_test))

Epoch 1/5
107/600 [====>.........................] - ETA: 8:12 - loss: 1.3043 - accuracy: 0.5393

In [ ]:
# EVALUATE THE LOSS AND ACCURACY OF RNN MODEL

loss, accuracy = model.evaluate(X_test, Y_test, verbose = 0)
print("Loss of the model is:", loss)
print("Accuracy of the model is:", (accuracy))