# Tutorial 8-Python Numpy Arrays

# Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

# What is an array?

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [1]:
# import the library
import numpy as np

In [2]:
lst = [1,2,3,4,5]
# create a numpy array
arr = np.array(lst)
print(arr)

[1 2 3 4 5]


In [3]:
print(type(arr)) # This type is a single dimension numpy array

<class 'numpy.ndarray'>


In [11]:
# size of the array
print(arr.size)

5


In [9]:
arr.ndim # one dimensional array

1

In [4]:
# shape of numpy array
x = arr.shape
print(x)

(5,)


In [5]:
lst1=[1,2,3,4,5]
lst2=[2,3,4,5,6]
lst3=[3,4,5,6,7]

ans = np.array([lst1, lst2, lst3])

In [6]:
print(ans)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [7]:
print(type(ans))

<class 'numpy.ndarray'>


In [8]:
ans.ndim # two dimensional array

2

In [10]:
# shape of the array
ans = ans.shape
print(ans)

(3, 5)


In [16]:
# indexing
arr = [1,2,3,4,5]
print(arr[3])

4


In [17]:
# modification in element of array
arr[4] = 10
print(arr)

[1, 2, 3, 4, 10]


In [18]:
print(arr[1:])

[2, 3, 4, 10]


In [21]:
# reversing all the elements in the array
print(arr)

[1, 2, 3, 4, 10]


In [22]:
a1 = arr[-5:-1]
print(a1)

[1, 2, 3, 4]


In [25]:
a2 = arr[-4:-2]
print(a2)

[2, 3]


In [26]:
a3 = arr[-5:-3]
print(a3)

[1, 2]


In [27]:
# take the last element
a4 = arr[:-1]
print(a4)

[1, 2, 3, 4]


In [28]:
arr[::]

[1, 2, 3, 4, 10]

In [29]:
arr[::-1]

[10, 4, 3, 2, 1]

In [30]:
arr[::-2]

[10, 3, 1]

In [31]:
arr[::-3]

[10, 2]

In [43]:
arr1 = [lst1, lst2, lst3]

In [44]:
print(arr1)

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]


In [46]:
# shape
sans = np.array(arr1)
print(sans)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [47]:
print(type(sans))

<class 'numpy.ndarray'>


In [48]:
print(sans.ndim)

2


In [49]:
print(sans.shape)

(3, 5)


In [50]:
# Indexing
print(sans[0,1:4])

[2 3 4]


In [51]:
print(sans[1:,1:3])

[[3 4]
 [4 5]]


In [52]:
print(sans[1:,3:])

[[5 6]
 [6 7]]


In [57]:
# EDA

In [58]:
arr = np.array([1,2,3,4,5])

In [61]:
arr[arr<2]

array([1])

In [62]:
arr1

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7]]

In [63]:
type(arr1)

list

In [64]:
arr1 = np.array(arr1)

In [65]:
print(type(arr1))

<class 'numpy.ndarray'>


In [66]:
# reshape the array
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


In [67]:
arr1 = arr1.reshape(5,3)
print(arr1)

[[1 2 3]
 [4 5 2]
 [3 4 5]
 [6 3 4]
 [5 6 7]]


In [71]:
##mechanism to create an array
x = np.arange(1,20,2)

In [72]:
print(x)

[ 1  3  5  7  9 11 13 15 17 19]


In [73]:
print(type(x))

<class 'numpy.ndarray'>


In [74]:
x = x.reshape(5,2)

In [75]:
print(x)

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [76]:
x = x.reshape(2,5,1)

In [77]:
print(x)

[[[ 1]
  [ 3]
  [ 5]
  [ 7]
  [ 9]]

 [[11]
  [13]
  [15]
  [17]
  [19]]]


In [78]:
arr

array([1, 2, 3, 4, 5])

In [79]:
arr * arr

array([ 1,  4,  9, 16, 25])

In [80]:
arr1

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [81]:
arr1 * 2

array([[ 2,  4,  6],
       [ 8, 10,  4],
       [ 6,  8, 10],
       [12,  6,  8],
       [10, 12, 14]])

In [82]:
arr1 * arr1 # dot product

array([[ 1,  4,  9],
       [16, 25,  4],
       [ 9, 16, 25],
       [36,  9, 16],
       [25, 36, 49]])

In [83]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [84]:
np.zeros((6,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [92]:
np.random.randint(10,50,9).reshape(3,3)

array([[19, 14, 47],
       [45, 11, 35],
       [35, 48, 24]])

In [93]:
np.random.randint(5,6)

5

In [94]:
np.random.randn(5,6)

array([[-0.32851381,  0.18067126, -0.72376459, -0.36184172,  0.10227899,
        -0.93950214],
       [ 0.78442878,  0.64852214, -2.26565427,  0.38410784, -0.08215784,
         0.21684397],
       [ 0.44956804,  0.99739912, -0.84175248,  0.03591263, -0.37418413,
         0.72118097],
       [ 0.23181457,  0.34531212,  0.51984454,  1.54559046,  0.5805394 ,
        -0.10566474],
       [ 0.57714498, -0.97852816, -0.0026778 ,  1.10259941,  0.04162365,
        -0.13725496]])

In [95]:
np.random.random_sample((5,6))

array([[0.58000464, 0.88425946, 0.39248355, 0.30512725, 0.19387928,
        0.42405316],
       [0.51642   , 0.2569835 , 0.59563579, 0.10544542, 0.30784   ,
        0.95552519],
       [0.54160231, 0.70055161, 0.93768516, 0.57017608, 0.17144771,
        0.19807726],
       [0.2398199 , 0.13791781, 0.4618221 , 0.51503142, 0.18926515,
        0.09257462],
       [0.12324897, 0.49707639, 0.77115341, 0.96574775, 0.07951854,
        0.57289453]])